name: Web Crawler
run-name: Daily Exchange & Monthly Rev & Seasonal reports & News Crawler

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:  # allow manual action

env:
  DB_CONNECTION: ${{ secrets.GCP_MYSQL_CONFIG }}

jobs:
  Setup-python-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Create Virtual Environment
        run: python -m venv web_scraper
      - name: Activate & Install packages & Run py files
        run: |
          source web_scraper/bin/activate
          pip install pandas requests lxml html5lib pymysql sqlalchemy twstock beautifulsoup4 cryptography
          twstock -U
          python ./src/news_crawler/get_anue_daily_news.py
          python ./src/financial_crawler/fetch_daily_exchange.py
          python ./src/financial_crawler/fetch_monthly_revenue.py
          python ./src/news_crawler/get_yahoo_daily_news.py
          python ./src/financial_crawler/main_seasonal_report.py
