name: Web Crawler
run-name: Daily Exchange & Monthly Rev & Seasonal reports & News Crawler

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:  # allow manual action

env:
  DB_CONNECTION: ${{ secrets.GCP_MYSQL_CONFIG }}

jobs:
  Setup-python-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Create Virtual Environment
        run: python -m venv web_scraper
      - name: Install Dependencies
        run: |
          source web_scraper/bin/activate
          pip install pandas requests lxml html5lib pymysql sqlalchemy twstock beautifulsoup4
          twstock -U
          python ./src/news_crawler/get_yahoo_daily_news.py
  Anue-daily-news:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
      - name: Restore Virtual Environment
        uses: actions/cache@v3
        with:
          path: web_scraper
          key: ${{ runner.os }}-web_scraper-${{ hashFiles('requirements.txt') }}
      - name: Run Anue Daily News Scraper
        run: |
          source web_scraper/bin/activate
          python ./src/news_crawler/get_anue_daily_news.py

  Yahoo-weekly-news:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
      - name: Run Weekly Weekly Yahoo News Scraper
        run: |
          source web_scraper/bin/activate
          twstock -U
          python ./src/news_crawler/get_yahoo_daily_news.py

  Daily-exchange-data:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
      - name: Restore Virtual Environment
        uses: actions/cache@v3
        with:
          path: web_scraper
          key: ${{ runner.os }}-web_scraper-${{ hashFiles('requirements.txt') }}
      - name: Run Daily Exchange Data Scraper
        run: |
          source web_scraper/bin/activate
          twstock -U
          python ./src/financial_crawler/fetch_daily_exchange.py

  Fetch-monthly-revenue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
      - name: Restore Virtual Environment
        uses: actions/cache@v3
        with:
          path: web_scraper
          key: ${{ runner.os }}-web_scraper-${{ hashFiles('requirements.txt') }}
      - name: Run Monthly Revenue Scraper
        run: |
          source web_scraper/bin/activate
          python ./src/financial_crawler/fetch_monthly_revenue.py

  Fetch-seasonal-reports:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4
      - name: Restore Virtual Environment
        uses: actions/cache@v3
        with:
          path: web_scraper
          key: ${{ runner.os }}-web_scraper-${{ hashFiles('requirements.txt') }}
      - name: Run Seasonal Report Scraper
        run: |
          source web_scraper/bin/activate
          python ./src/financial_crawler/main_seasonal_report.py
